spring:
  cloud:
    stream:
      kafka:
        binder:
          # Bootstrap connection to Kafka
          brokers: localhost:9092
          configuration:
            auto:
              offset:
                reset: earliest
      bindings:
        input:
          group: input
          binder: kafka1
          destination: test_in
        output:
          group: output
          binder: rabbit1
          destination: test_out
      binders:
        kafka1:
          defaultCandidate: false
          type: kafka
        rabbit1:
          defaultCandidate: false
          type: rabbit
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

logging:
  level:
    org.apache: INFO
    org.springframework.cloud.stream.*: WARN
